# Generated by Django 2.2.7 on 2019-11-29 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=30, verbose_name='Nombre de categoría')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='Linkage',
            fields=[
                ('linkage_id', models.AutoField(primary_key=True, serialize=False)),
                ('linkage_name', models.CharField(max_length=30, verbose_name='Nombre de vinculación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['linkage_name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_dni', models.BigIntegerField(verbose_name='Documento de identidad')),
                ('teacher_name', models.CharField(max_length=30, verbose_name='Primer nombre')),
                ('teacher_middle_name', models.CharField(max_length=30, verbose_name='Segundo nombre')),
                ('teacher_last_name', models.CharField(max_length=30, verbose_name='Primer apellido')),
                ('teacher_middle_last_name', models.CharField(max_length=30, verbose_name='Segundo apellido')),
                ('teacher_status', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher_category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teacher.Category')),
                ('teacher_linkage_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teacher.Linkage')),
            ],
        ),
    ]
