# Generated by Django 2.2.7 on 2019-11-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_dni',
            field=models.CharField(max_length=20, verbose_name='Documento de identidad'),
        ),
    ]
