# Generated by Django 2.2.7 on 2019-11-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20191130_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Primer apellido'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Primer nombre'),
        ),
    ]
