# Generated by Django 2.2.7 on 2019-11-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20191130_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_middle_last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Segundo apellido'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_middle_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Segundo nombre'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_name',
            field=models.CharField(max_length=30, verbose_name='Primer nombre'),
        ),
    ]
