# Generated by Django 2.2.7 on 2019-11-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20191130_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_last_name',
            field=models.CharField(max_length=30, verbose_name='Primer apellido'),
        ),
    ]
