# Generated by Django 2.2.7 on 2019-12-11 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_auto_20191130_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('study_id', models.AutoField(primary_key=True, serialize=False)),
                ('study_type', models.CharField(choices=[('PREGRADO', 'Pregrado'), ('ESPECIALIZACION', 'Especialización'), ('MAESTRIA', 'Maestría'), ('DOCTORADO', 'Doctorado'), ('POS_DOCTORADO', 'Pos-doctorado')], default='PREGRADO', max_length=20)),
                ('study_name', models.CharField(max_length=100, verbose_name='Nombre del estudio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('study_teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teacher.Teacher')),
            ],
        ),
    ]
