# Generated by Django 2.2.7 on 2019-12-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_auto_20191212_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
