# Generated by Django 2.2.7 on 2019-12-26 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('career_id', models.AutoField(primary_key=True, serialize=False)),
                ('career_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('subject_code', models.CharField(max_length=10)),
                ('subject_name', models.CharField(max_length=60)),
                ('subject_credits', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('resolution_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('resolution_start_date', models.DateField()),
                ('resolution_end_date', models.DateField()),
                ('resolution_hours', models.IntegerField()),
                ('resolution_total_qualification', models.FloatField()),
                ('resolution_total_seedbed', models.FloatField()),
                ('resolution_total_group', models.FloatField()),
                ('resolution_total_teacher', models.FloatField()),
                ('resolution_category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teacher.Category')),
                ('resolution_linkage_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teacher.Linkage')),
                ('resolution_teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teacher.Teacher')),
            ],
        ),
    ]
