# Generated by Django 2.2.7 on 2019-12-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
