# Generated by Django 2.2.7 on 2019-12-12 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolution', '0002_auto_20191212_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolution',
            name='resolution_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
